### PR TITLE
Close containerd-env file before restarting service

### LINKED ISSUE #22: Running behind proxy requires manual stop / start
Either deploying or changing the containerd and / or coredns config to support being behind a proxy requires a manual stop / start step to fully restart microk8s before the pods will pick up the updated config. Until then, the node stays stuck in `NotReady` due to containerd failing to pull the Calico images.

### PR DESCRIPTION
**Pull request by johnsca**
Fixes #22

### CODE REVIEW

**Review by neoaggelos — APPROVED** [review]
LGTM, good catch!

**Comment by johnsca** [comment]
I'm not sure why it's claiming I didn't sign the CLA.

**Comment by johnsca** [comment]
Also unsure about the integration test failure.  It looks like it timed out on enabling `coredns` due to this error:

```
Failed to get coredns configmap!  kubectl said: b'Error from server (NotFound): configmaps "coredns" not found\n'
```

I don't think that's related to this change and may be a transient error because I've been using this branch and have never encountered that.

**Comment by neoaggelos** [comment]
The integration tests are simply slightly flaky due to limitations in the GitHub runner resources.

Regarding the CLA check, perhaps it's the email on the commit that's causing the issues?

**Comment by johnsca** [comment]
My GH account has my Canonical email address on it as well, and I've even explicitly signed it previously, so it definitely should be able to see that I've signed it.

**Pull request merged**
